export const STOCK_DB_FIREBASE_FIRE_STORE = 'stock-market-lk';
export const DSD = 'stock-market-lk';
export const FIREBASE_CONFIG_COMPANIES_STOCK_MARKET_DATA = 'COMPANIES_STOCK_MARKET_DATA';

export const FIREBASE_CONFIG = {
  apiKey: process.env.REACT_APP_FIREBASE_API_KEY,
  authDomain: process.env.REACT_APP_AUTH_DOMAIN,
  projectId: process.env.REACT_APP_PROJECT_ID,
  storageBucket: process.env.REACT_APP_STORAGE_BUCKET,
  messagingSenderId: process.env.REACT_APP_MESSAGING_SENDER_ID,
  appId: process.env.REACT_APP_APP_ID,
  measurementId: process.env.REACT_APP_MEASUREMENT_ID,
};

export const STOCKS_META_DATA_FIRESTORE = {
  HIGH_PRICE: 'highPrice',
  LOW_PRICE: 'lowPrice',
  SHARES_VOLUME: 'shareVolume',
  TRADE_VOLUME: 'tradeVolume',
};

export const ACTION_TYPES_DAILY_DATA = {
  HIGH_PRICE: 'HIGH_PRICE',
  LOW_PRICE: 'LOW_PRICE',
  SHARES_VOLUME: 'SHARES_VOLUME',
  TRADE_VOLUME: 'TRADE_VOLUME',
  DATE_ONLY: 'DATE_ONLY',
};

export const TITLES_DAILY_DATA = {
  HIGH_PRICE: 'HIGH PRICE',
  LOW_PRICE: 'LOW PRICE',
  SHARES_VOLUME: 'SHARES VOLUME',
  TRADE_VOLUME: 'TRADE VOLUME',
};

export const BUTTON_POSITIONS = {
  BOTTOM_RIGHT_CORNER: 'BOTTOM_RIGHT_CORNER',
  BOTTOM_RIGHT_CORNER_PREVIOUS: 'BOTTOM_RIGHT_CORNER_PREVIOUS',
  TOP_RIGHT_CORNER: 'TOP_RIGHT_CORNER',
};

export const LOW_PRICE_COLOR_CODES = {
  GRAPH_BORDER_COLOR: '#92D293',
  GRAPH_BACKGROUND_COLOR: '#4F7942',
};

export const HIGH_PRICE_COLOR_CODES = {
  GRAPH_BORDER_COLOR: '#D2686E',
  GRAPH_BACKGROUND_COLOR: '#7C494C',
};

export const DEFAULT_DATA_SET_STATE = [
  {
    label: TITLES_DAILY_DATA.HIGH_PRICE,
    data: [],
    borderColor: HIGH_PRICE_COLOR_CODES.GRAPH_BORDER_COLOR,
    backgroundColor: HIGH_PRICE_COLOR_CODES.GRAPH_BACKGROUND_COLOR,
  },
  {
    label: TITLES_DAILY_DATA.LOW_PRICE,
    data: [],
    borderColor: LOW_PRICE_COLOR_CODES.GRAPH_BORDER_COLOR,
    backgroundColor: LOW_PRICE_COLOR_CODES.GRAPH_BACKGROUND_COLOR,
  },
];
